### ISSUE TITLE
replaceTextToImage not working

### ISSUE THREAD

**Issue by nan4k7** [igorrebega/docx-replacer#2]
Hi! I'm having problems using "replaceTextToImage". Whenever I do that I get a docx that gives me an error when I open it saying:

> "We're sorry. We can't open export.docx because we found a problem with its contents." Details: "The file is corrupt and cannot be opened"

My lines of code are:

```
require_once("include/docx-replacer/vendor/autoload.php");

$file = "precontratos/".$castingid.".docx";

if (!file_exists($file))
	die("not found");

$tempFile = "tmp/".md5(date("ymdHisu")).".docx";
copy($file, $tempFile) or die("error");

$docx = new IRebega\DocxReplacer\Docx($tempFile);

$tablaCache = "imagesCastingsCache/".$castingid.".jpg";

if (file_exists($tablaCache))
	$docx->replaceTextToImage("{TABLACACHE}", $tablaCache);
else
	$docx->replaceText("{TABLACACHE}", "");
```

Any help would be apreciated. 

I'm attaching the resulting docx. [export.docx](https://github.com/igorrebega/docx-replacer/files/1892384/export.docx)

**Comment by igorrebega** [comment]
Hello @nan4k7. Can you try update package to the newest version? Looks like I don`t predict all cases in previous release

**Comment by nan4k7** [comment]
Sure! Here you have it...

[YPF_precontrato.new.docx](https://github.com/igorrebega/docx-replacer/files/1894766/YPF_precontrato.new.docx)

**Comment by igorrebega** [comment]
Also I can`t reproduce same error as you( If error will appear again, please describe by step how I can reproduce it on my machine

**Comment by nan4k7** [comment]
I fixed the docx so as to be correct... Here it is: [YPF_precontrato.new.docx](https://github.com/igorrebega/docx-replacer/files/1895759/YPF_precontrato.new.docx)

The following code still gives me an error (I've already updated the docx-replacer with composer)

```
require_once("include/docx-replacer/vendor/autoload.php");

$tempFile = "tmp/".md5($nombre.$edad.$castings_nombre.date("ymdHisu")).".docx";

$docx = new IRebega\DocxReplacer\Docx($tempFile);

$tablaCache = "imagesCastingsCache/".$castingid.".jpg";

if (file_exists($tablaCache))
	$docx->replaceTextToImage("${TABLACACHE}", $tablaCache);
else
	$docx->replaceText("${TABLACACHE}", "");

$docx->replaceText("${NOMBRE}", $nombre);
$docx->replaceText("${DNI}", $dni);
$docx->replaceText("${SEXO}", $sexo);
$docx->replaceText("${CUIT}", $cuit);
$docx->replaceText("${AGENCIA}", $agencia);
$docx->replaceText("${PREPAGA}", $prepaga);
$docx->replaceText("${CELULAR}", $celular);
$docx->replaceText("${TELEFONO}", $telefono);
$docx->replaceText("${EDAD}", $edad);
$docx->replaceText("${NACIMIENTO}", $nacimiento);
$docx->replaceText("${DOCIMILIO}", $domicilio);
$docx->replaceText("${MAIL}", $mail);
$docx->replaceText("${ALTURA}", $altura);
$docx->replaceText("${CAMISA}", $camisa);
$docx->replaceText("${PANTALON}", $pantalon);
$docx->replaceText("${CALZADO}", $calzado);

$docx->replaceText("${NOMBRECAST}", $castings_nombre);
$docx->replaceText("${CAMPAÑA}", $castings_campania);
$docx->replaceText("${PRODUCTORA}", $castings_productora);
$docx->replaceText("${SHOOTDATE}", $castings_shootdate);
$docx->replaceText("${SHOOTLOCATION}", $castings_shootlocation);
$docx->replaceText("${CALLBACK}", $castings_callback);
$docx->replaceText("${PRUEBAVEST}", $castings_pruebavest);
$docx->replaceText("${FECHA}", $castings_fecha);

```

> Fatal error: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /var/www/clients/client4/web25/web/saigon/include/docx-replacer/vendor/irebega/docx-replacer/src/Docx.php:144 Stack trace: #0 /var/www/clients/client4/web25/web/saigon/include/docx-replacer/vendor/irebega/docx-replacer/src/Docx.php(144): SimpleXMLElement->__construct('') #1 /var/www/clients/client4/web25/web/saigon/include/docx-replacer/vendor/irebega/docx-replacer/src/Docx.php(69): IRebega\DocxReplacer\Docx->addRel('http://schemas....', 'media/nEOhzoDcv...') #2 /var/www/clients/client4/web25/web/saigon/ddWord.php(150): IRebega\DocxReplacer\Docx->replaceTextToImage('', 'imagesCastingsC...') #3 {main} thrown in /var/www/clients/client4/web25/web/saigon/include/docx-replacer/vendor/irebega/docx-replacer/src/Docx.php on line 144



I edited docx.php and added a die after line 144 so as to show vars

```
        $file = $this->getFromName(self::REL_LOCATION);
		die(self::REL_LOCATION . " / " . $file);
```

and $file var seems to be empty because that outputs: 

> word/_rels/document.xml.rels / 


Thanks for your help

**Comment by igorrebega** [comment]
Hm, the problem is in my case all works, and the image got updated.

Looks like the error is about a php-zip library, does a usual text `replaceText`? Because as I can see you have "word/_rels/document.xml.rels" file and he is not empty.

![image](https://user-images.githubusercontent.com/2010915/38604741-fcbb7a90-3d79-11e8-9a4e-38fab68af4cf.png)

Please contact me on [t.me/irebega](https://t.me/irebega). I suppose this way we can solve your problem faster

**Comment by igorrebega** [comment]
I suppose this issue can be closed now because of inactivity

**Comment by C-Nedelcu** [comment]
Hello,

I am encountering the same error as reported in the first post: "We're sorry. We can't open export.docx because we found a problem with its contents."

Then Word asks whether I want to try and recover the file. I press OK and Word does show the file, with the image, but the image size is way off (it shows huge, but the original image is only 150x150)

- I have made sure to use the last version of source code and XML file.
- I used the same code example as on the readme.
- I am trying with a very simple Docx file (create new file, insert the word "test" and save)
- Standard jpg image 150x150
